apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: wsrr-setdbparms-01
spec:
  type: setdbparms
  data: mqsisetdbparms -w /home/aceuser/ace-server -n Identity -u dummy -p dumPass
